#!/bin/bash

iniciar(){

# Abre para a faixa de endereços da rede local:

iptables -A INPUT -i lo -j ACCEPT

iptables -A INPUT -p tcp --syn -j DROP

# Faz a mesma coisa, só que especificando a interface. Pode ser

# usada em substituição à regra anterior:

# iptables -A INPUT -i eth0 -j ACCEPT

# Abre uma porta (inclusive para a Internet):

iptables -A INPUT -p tcp --dport 22 -j DROP

# Ignora pings:

iptables -A INPUT -p icmp --icmp-type echo-request -j DROP

# Protege contra IP spoofing:

echo 1 > /proc/sys/net/ipv4/conf/default/rp_filter

# Descarta pacotes malformados, protegendo contra ataques diversos:

iptables -A INPUT -m state --state INVALID -j DROP

# Abre para a interface de loopback. Esta regra é essencial para que

# o KDE e outros programas gráficos funcionem adequadamente:

iptables -A INPUT -i lo -j ACCEPT

# Impede a abertura de novas conexões, efetivamente bloqueando o acesso

# externo ao seu servidor, com exceção das portas e faixas de endereços

# especificadas anteriormente:

iptables -A INPUT -p tcp --syn -j DROP

echo "Regras de firewall ativadas"

}

parar(){

iptables -F

iptables -P INPUT ACCEPT

iptables -P OUTPUT ACCEPT

echo "Regras de firewall desativadas"

}

case "$1" in

"start") iniciar ;;

"stop") parar ;;

"restart") parar; iniciar ;;

*) echo "Use os parâmetros start ou stop"

esac
